Repository latitude-dev/latitude-llm, pull requests merged in 2024-10, with the labels that each got.

#335 Evaluation results by document content + diff editor apparently
  apps/web/src/app/api/documents/[projectId]/[commitUuid]/[documentUuid]/evaluation-results-by-document-content/[evaluationId]/route.ts
  apps/web/src/services/routes.ts
  apps/web/src/services/routes/api.ts
  apps/web/src/stores/connectedEvaluations.ts
  apps/web/src/stores/documentLogWithMetadata.ts
  apps/web/src/stores/documentVersions.ts
  apps/web/src/stores/documentsForImport.ts
  apps/web/src/stores/evaluationResultsByDocumentContent.ts
  packages/core/drizzle/0063_curly_logan.sql
  packages/core/drizzle/meta/0063_snapshot.json
  packages/core/drizzle/meta/_journal.json
  packages/core/src/lib/hashContent.ts
  packages/core/src/lib/index.ts
  packages/core/src/repositories/documentVersionsRepository/getDocumentAtCommit.test.ts
  packages/core/src/repositories/evaluationResultsRepository/index.ts
  packages/core/src/schema/models/documentLogs.ts
  packages/core/src/schema/models/documentVersions.ts
  packages/core/src/services/documentLogs/create.ts
  packages/core/src/services/documents/recomputeChanges/index.ts
  packages/core/src/services/evaluationResults/computeEvaluationResultsByDocumentContent.test.ts
  packages/core/src/services/evaluationResults/computeEvaluationResultsByDocumentContent.ts
  packages/core/src/services/evaluationResults/index.ts
  packages/web-ui/src/ds/molecules/DocumentTextEditor/Editor/DiffEditor.tsx
  packages/web-ui/src/ds/molecules/DocumentTextEditor/Editor/EditorWrapper.tsx
  packages/web-ui/src/ds/molecules/DocumentTextEditor/Editor/RegularEditor.tsx
  packages/web-ui/src/ds/molecules/DocumentTextEditor/Editor/actions.ts
  packages/web-ui/src/ds/molecules/DocumentTextEditor/Editor/index.tsx
  packages/web-ui/src/ds/molecules/DocumentTextEditor/Editor/language.ts
  packages/web-ui/src/ds/molecules/DocumentTextEditor/Editor/useEditorOptions.ts
  packages/web-ui/src/ds/molecules/DocumentTextEditor/Editor/useMonacoSetup.ts
  packages/web-ui/src/ds/molecules/DocumentTextEditor/editor.tsx
  packages/web-ui/src/ds/molecules/DocumentTextEditor/index.tsx
  packages/web-ui/src/ds/molecules/DocumentTextEditor/types.ts
Labels: 🚂 lil train

#378 Extended and paginated results on refine modal
  .vscode/launch.json
  apps/web/src/app/(private)/projects/[projectId]/versions/[commitUuid]/documents/[documentUuid]/_components/DocumentEditor/Editor/RefineModal/steps/2_SelectEvaluationResults/SelectableEvaluationResultsTable.tsx
  apps/web/src/app/(private)/projects/[projectId]/versions/[commitUuid]/documents/[documentUuid]/_components/DocumentEditor/Editor/RefineModal/steps/2_SelectEvaluationResults/index.tsx
  apps/web/src/app/api/documents/[projectId]/[commitUuid]/[documentUuid]/evaluation-results-by-document-content/[evaluationId]/route.ts
  apps/web/src/stores/evaluationResultsByDocumentContent.ts
  packages/core/src/repositories/evaluationResultsRepository/index.ts
  packages/core/src/services/evaluationResults/_createEvaluationResultQuery.ts
  packages/core/src/services/evaluationResults/computeEvaluationResultsByDocumentContent.test.ts
  packages/core/src/services/evaluationResults/computeEvaluationResultsByDocumentContent.ts
Labels: 🚧 wip

#395 Fix LATITUDE-LLM-APP-3C
  packages/core/src/repositories/workspacesRepository.ts
Labels: 🐛 bug

#402 Fix LATITUDE-LLM-APP-3S swapped mode and mean evaluation aggr components
  apps/web/src/components/EvaluationAggregatedResult/index.tsx
Labels: 🐛 bug

#325 feature: blue/green deployments for gateway
  .github/workflows/ci.yml
  .github/workflows/deploy-gateway.yml
  apps/gateway/appspec.yml
  apps/infra/src/app/production/gateway.ts
  apps/infra/src/app/production/web.ts
  apps/infra/src/docker/production/gateway.ts
Labels: 🚧 wip

#503 Implement nextjs middleware to check auth
  apps/web/src/app/(private)/dashboard/layout.tsx
  apps/web/src/middleware.ts
  apps/web/src/services/auth/constants.ts
  apps/web/src/services/auth/index.ts
  apps/web/src/services/routes.ts
Labels: 🐛 bug
